### ISSUE TITLE
Duplicate DerelictTheme generation

### ISSUE THREAD

**Issue by Silver-D** [Lukas22041/Random-Assortment-of-Things#1]
Hi! I found a bug with the ThemeGenerator

in RATSectorThemeGenerator on line 34

`if (gen instanceof RemnantThemeGenerator || gen instanceof RuinsThemeGenerator || gen instanceof MiscellaneousThemeGenerator || gen instanceof RATDerelictThemeGenerator) continue;`

It is testing for RATDerelictThemeGenerator  and not DerelictThemeGenerator, adding the vanilla to the gen array, making both the vanilla and the RAT version to fire. This creates duplicates of motherships and cryosleepers.

And another small thing is that the RATMiscellaneousThemeGenerator is missing some tag checking for NOT_RANDOM_MISSION_TARGET that were added in a couple of minor RC updates to the vanilla Misc Generator.

Absolutely love your mod btw, just saw the update and holy smooookes that's a changelist if I've seen one.
Cheers!

**Comment by Lukas22041** [comment]
Not sure how i missed this issue, you are completely correct and i will fix those issues, thanks for bringing them up!
