### ISSUE TITLE
Fatal: Null

### ISSUE THREAD

**Issue by TriLea** [Lukas22041/Random-Assortment-of-Things#6]
I updated Rat from 1.6 something, and I updated lunaLib, but now when I try to load Rat I get a Fatal: Null, I tried to fix the problem, by updating and check all my mods but I could not find the issue.

here is the last line I got in the starsector.log1 "19272 [Thread-3] INFO  com.fs.starfarer.campaign.rules.Rules  - Loading rule: swpBTCompletionStartFleetCutOffB1"

I'm sorry I don't have a better report.

**Comment by Lukas22041** [comment]
"swpBTCompletionStartFleetCutOffB1" swp is probably Ship & Weapons Pack, also not all updates are save-compatible.
